# Profile para conectar a API ao MySQL da faculdade.
# Informe os valores por variáveis de ambiente para evitar senha no código.
spring.datasource.url=${jdbc:postgresql://dpg-d7amf05actks73c1m0bg-a:5432/physiquedb}
spring.datasource.username=${physiquedb_user}
spring.datasource.password=${sruQSmBTTLEc1XxwcX1oLDrV9ccH146q}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.h2.console.enabled=false
